# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QKV3eBB6bZOqEdGUEsPth2DrvfuKctu7

# Семинар 9 

**Задача 57.**

Прочесть с помощью pandas файл california_housing_test.csv, который находится в папке sample_data

Используем метод пандос
"""

import pandas as pd

"""Задаем переменную"""

f = pd.read_csv('sample_data/california_housing_test.csv')

"""Смотреть размер"""

f.shape

"""Определяем тип данных"""

f.dtypes

"""**Задача №59. ** 

Проверить есть ли в файле пустые значки

Показать median_house где median_income < 2

Выбрать данные в первых 2 столбцах 

Выбрать данные где housing_median_age < 20 и median_house_value > 70000
"""

import pandas as pd

f = pd.read_csv('sample_data/california_housing_test.csv')

"""Находим сумму"""

f.isnull().sum

"""Выводим столбец"""

f['median_house_value']

"""Находим среднее"""

f['median_house_value'].mean()

"""Показать median_house где median_income < 2"""

f[f['median_income'] < 2] ['median_house_value']

f[f['median_income'] < 2]

"""Показываем первые два столбца"""

f[['longitlongitude	latitude

"""Выбрать данные где housing_median_age < 20 и median_house_value > 70000"""

f[(f['housing_median_age'] < 20) & (f['median_house_value'] > 70000)]

"""**Задача №61. **

1. Определить какое максимальное и минимальное значение median_house_value

2. Показать максимальное median_house_value, где median_income = 3.1250

3. Узнать какая максимальная population в зоне минимального значения median_house_value

Определить какое максимальное значение median_house_value
"""

f['median_house_value'].max()

"""Определить какое минимальное значение median_house_value"""

f['median_house_value'].min()

"""Показать максимальное median_house_value, где median_income = 3.1250"""

f[f['median_income'] == 3.1250]['median_house_value'].max()

"""Показать максимальное median_house_value, где median_income = 3.1250 и выводим столбци"""

f[f['median_income'] == 3.1250]['median_house_value'].max()

"""Узнать какая максимальная population в зоне минимального значения median_house_value"""

f[f['median_house_value'] == f['median_house_value'].min()]['population'].max()

"""Смотрим процентное соотношение 10%"""

f[f['median_house_value'] < f['median_house_value'].min()*10]['population'].max()