# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1I3MdyPvseeAAGkuW2Eoyk7BMGC8yp0GJ

# Задача №63. 

1. Изобразите отношение households к population с
помощью точечного графика
2. Визуализировать longitude по отношения к
median_house_value, используя линейный график
3. Представить гистограмму по housing_median_age
4. Изобразить гистограмму по median_house_value с
оттенком housing_median_age
"""

import seaborn as sns

import pandas as pd

f = pd.read_csv('sample_data/california_housing_train.csv')

"""Точечный ленейный график"""

sns.scatterplot(data=f, x="households", y="population")

"""Визуализировать longitude по отношения к median_house_value, используя линейный график"""

sns.relplot(x="longitude", y="median_house_value", kind="line", data=f)

"""Представить гистограмму по housing_median_age"""

sns.histplot(data=f, x="housing_median_age")

"""Изображаем гистограму по madian_house_value c оттенком housing_median_age"""

sns.displot(f, x="median_house_value", hue="huosing_median_age")

"""# Задача №65.

Написать EDA для датасета про пингвинов
Необходимо:

● Использовать 2-3 точечных графика

● Применить доп измерение в точечных графиках, используя аргументы hue, size, stile

● Использовать PairGrid с типом графика на ваш выбор

● Изобразить Heatmap

● Использовать 2-3 гистограммы

Чтобы подключить датасет с
пингвинами, воспользуйтесь данным
скриптом:
penguins = sns.load_dataset("penguins")
penguins.head()
"""

import pandas as pd
import seaborn as sns

f = pd.read_csv('sample_data/california_housing_test.csv')

f.shape

f.dtypes

f.isnull().sum()

sns.scatterplot(data=f, x="households", y="population")

penguins = sns.load_dataset("penguins")
penguins.head()

sns.scatterplot(data=penguins, x="body_mass_g", y="flipper_length_mm")

sns.scatterplot(data=penguins, x="body_mass_g", y="bill_depth_mm", hue="species")

"""sns.scatterplot(data=penguins, x="body_mass_g", y="bill_depth_mm", hue="species")"""

sns.scatterplot(data=penguins, x="body_mass_g", y="bill_lenght_mm", hue="species",size="flipper_length_mm")

glue = sns.load_dataset("glue").pivot("Model", "Task", "Score")
sns.heatmap(glue)

glue = sns.load_dataset("glue").pivot("Model", "Task", "Score")
sns.heatmap(glue, annot=True)

glue = sns.load_dataset("glue").pivot("Model", "Task", "Score")
sns.heatmap(glue, annot=True, linewidth=1)

glue = sns.load_dataset("glue").pivot("Model", "Task", "Score")
sns.heatmap(glue, annot=True, linewidth=1, cmap='crest')

glue.head()

sns.histplot(df)

sns.histplot(df, x='body_mass_g')

sns.histplot(df, x='flipper_length_mm', hue='species')

sns.histplot(df, x='body_mass_g', hue='sex')

"""# Задача №67.

1. Создать новый столбец в таблице с
пингвинами, который будет отвечать за
показатель длины клюва пингвина.
high - длинный(от 42)
middle - средний(от 35 до 42)
low - маленький(до 35)
Чтобы подключить датасет с
пингвинами, воспользуйтесь данным
скриптом:
penguins = sns.load_dataset("penguins")
penguins.head()

# Задача №69.

1. Изобразить гистограмму по flipper_length_mm
с оттенком height_group. Сделать анализ
"""