# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1i7jfvgSoL-Y6ISvd2dcWY-GWjfLKZyhr

# Задача 40: 

Работать с файлом california_housing_train.csv, который находится в папке
sample_data. Определить среднюю стоимость дома, где кол-во людей от 0 до 500 (population)
"""

import pandas as pd

f = pd.read_csv('sample_data/california_housing_train.csv')

f[(f['population'] > 0) & (f['population'] < 500)].median_house_value.mean()

"""# Задача 42: 

Узнать какая максимальная households в зоне минимального значения population
"""

f[f['population'] == f['population'].min()]['households'].max()